const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "mongodb+srv://DARKSHAN:3000@Ccluster0.t1wsjlv.mongodb.net/"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "2348057536207" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null.2348057536207";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2348057536207";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_03_23_05_10_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAwLFxuICAgICAgICAyMzIsXG4gICAgICAgIDE3LFxuICAgICAgICAxMjQsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTMxLFxuICAgICAgICAxMDQsXG4gICAgICAgIDkwLFxuICAgICAgICA5NixcbiAgICAgICAgMyxcbiAgICAgICAgNjEsXG4gICAgICAgIDk4LFxuICAgICAgICAyNDUsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTM1LFxuICAgICAgICA1NixcbiAgICAgICAgMjQxLFxuICAgICAgICAyMzMsXG4gICAgICAgIDk1LFxuICAgICAgICAyNDEsXG4gICAgICAgIDIyLFxuICAgICAgICAxNTIsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjE0LFxuICAgICAgICAzOSxcbiAgICAgICAgMjUyLFxuICAgICAgICAxNTgsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMjIzLFxuICAgICAgICAxOTYsXG4gICAgICAgIDE1MyxcbiAgICAgICAgNjRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM3LFxuICAgICAgICAxNjYsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTY4LFxuICAgICAgICAyMzQsXG4gICAgICAgIDE2OCxcbiAgICAgICAgNjksXG4gICAgICAgIDE2MSxcbiAgICAgICAgNzEsXG4gICAgICAgIDIzOSxcbiAgICAgICAgNTMsXG4gICAgICAgIDIyOCxcbiAgICAgICAgNyxcbiAgICAgICAgNjUsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjMyLFxuICAgICAgICAyNSxcbiAgICAgICAgMTMsXG4gICAgICAgIDY1LFxuICAgICAgICAxMjQsXG4gICAgICAgIDc5LFxuICAgICAgICAyMzQsXG4gICAgICAgIDYwLFxuICAgICAgICAyMSxcbiAgICAgICAgMjE3LFxuICAgICAgICAxMzEsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTMyLFxuICAgICAgICAxNzQsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMjI5LFxuICAgICAgICAxMDhcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzMixcbiAgICAgICAgMjQ1LFxuICAgICAgICAzMyxcbiAgICAgICAgNzcsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTE4LFxuICAgICAgICAxMzMsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjMxLFxuICAgICAgICA5OSxcbiAgICAgICAgMTE1LFxuICAgICAgICAxOTAsXG4gICAgICAgIDM2LFxuICAgICAgICAyNyxcbiAgICAgICAgMjI4LFxuICAgICAgICAyMjEsXG4gICAgICAgIDczLFxuICAgICAgICA2NCxcbiAgICAgICAgMTM2LFxuICAgICAgICA0MixcbiAgICAgICAgMTc4LFxuICAgICAgICAxNDYsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTcsXG4gICAgICAgIDU5LFxuICAgICAgICAxMTIsXG4gICAgICAgIDYzLFxuICAgICAgICAxMyxcbiAgICAgICAgMTkzLFxuICAgICAgICAxNSxcbiAgICAgICAgMTYwLFxuICAgICAgICA2NlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDcsXG4gICAgICAgIDk4LFxuICAgICAgICA5NyxcbiAgICAgICAgMjgsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTk5LFxuICAgICAgICA5NyxcbiAgICAgICAgMjE3LFxuICAgICAgICAxOTcsXG4gICAgICAgIDQsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTYyLFxuICAgICAgICAxMTcsXG4gICAgICAgIDI4LFxuICAgICAgICA4MCxcbiAgICAgICAgMTUyLFxuICAgICAgICAxNixcbiAgICAgICAgMTQ5LFxuICAgICAgICA3MixcbiAgICAgICAgMjQ5LFxuICAgICAgICA0MSxcbiAgICAgICAgMTA2LFxuICAgICAgICA5NixcbiAgICAgICAgODksXG4gICAgICAgIDYsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjM1LFxuICAgICAgICAyMTUsXG4gICAgICAgIDEwNixcbiAgICAgICAgMjAwLFxuICAgICAgICAxOTIsXG4gICAgICAgIDE3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNixcbiAgICAgICAgMjE3LFxuICAgICAgICAyMDAsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMjQsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTg1LFxuICAgICAgICAxNTIsXG4gICAgICAgIDg2LFxuICAgICAgICAxMjMsXG4gICAgICAgIDYxLFxuICAgICAgICAxNzAsXG4gICAgICAgIDI0LFxuICAgICAgICA2NCxcbiAgICAgICAgMjksXG4gICAgICAgIDU0LFxuICAgICAgICAxMDIsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMjMsXG4gICAgICAgIDIxLFxuICAgICAgICA3OSxcbiAgICAgICAgNTksXG4gICAgICAgIDEwNixcbiAgICAgICAgMjM2LFxuICAgICAgICAyMzgsXG4gICAgICAgIDE0NyxcbiAgICAgICAgODAsXG4gICAgICAgIDUzLFxuICAgICAgICA3LFxuICAgICAgICAxMzQsXG4gICAgICAgIDEwOVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTIsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxMDgsXG4gICAgICAgIDM3LFxuICAgICAgICAxNDUsXG4gICAgICAgIDU0LFxuICAgICAgICAxMDYsXG4gICAgICAgIDMxLFxuICAgICAgICAxMDAsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTE1LFxuICAgICAgICAyMTgsXG4gICAgICAgIDY1LFxuICAgICAgICA3NyxcbiAgICAgICAgMTUwLFxuICAgICAgICA4NixcbiAgICAgICAgMTI3LFxuICAgICAgICA3MyxcbiAgICAgICAgOTAsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTgxLFxuICAgICAgICAxOTEsXG4gICAgICAgIDk4LFxuICAgICAgICAyMDYsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMzgsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTI5LFxuICAgICAgICAxODIsXG4gICAgICAgIDM0LFxuICAgICAgICAxMjVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAzNSxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAyOCxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgMTE5XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIxMixcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgNCxcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgODksXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgNixcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICA1MlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjA4LFxuICAgICAgICAxNTQsXG4gICAgICAgIDc2LFxuICAgICAgICA3MyxcbiAgICAgICAgMTUsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTIzLFxuICAgICAgICAxMTAsXG4gICAgICAgIDI1LFxuICAgICAgICAxMjYsXG4gICAgICAgIDk4LFxuICAgICAgICAzMyxcbiAgICAgICAgODIsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTE2LFxuICAgICAgICAyMDUsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTA3LFxuICAgICAgICA5MSxcbiAgICAgICAgMTcyLFxuICAgICAgICAxMzcsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjA4LFxuICAgICAgICAxMyxcbiAgICAgICAgMjExLFxuICAgICAgICA0OSxcbiAgICAgICAgMjI4LFxuICAgICAgICAyMDgsXG4gICAgICAgIDYsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTUwLFxuICAgICAgICAyMDAsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjI0LFxuICAgICAgICA0OSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNzgsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTU0LFxuICAgICAgICAxOCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxOTgsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTI5LFxuICAgICAgICAxMTQsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMjA2LFxuICAgICAgICAxNzMsXG4gICAgICAgIDExOCxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMjYsXG4gICAgICAgIDgyLFxuICAgICAgICAxNzcsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTYyLFxuICAgICAgICAxNDMsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTg4LFxuICAgICAgICAyNTAsXG4gICAgICAgIDE2NyxcbiAgICAgICAgNCxcbiAgICAgICAgMTg2LFxuICAgICAgICAwXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAzMCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJpRmVQNTRWaTZGNlExd2lsd2FRZEozVG5MOUtseVhjN0Z1c1RWTGx5WmpZPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDgwNTc1MzYyMDdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjg3OUFCNzU2RDgzMDcyNEMyMzhBNkU5RjM5Njk3QzY2XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNTMxMTM4NFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJIUHl3Vzd6Y1J6V2FWbENhR3pVbW53XCIsXG4gIFwicGhvbmVJZFwiOiBcImYwOWYwYWM2LWEzYjctNGMwNi1hMTY5LWQzZTRiNTI0MTMzYlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA4MyxcbiAgICAgIDEyNSxcbiAgICAgIDEzMCxcbiAgICAgIDg4LFxuICAgICAgMTY3LFxuICAgICAgMTY1LFxuICAgICAgMTk3LFxuICAgICAgOSxcbiAgICAgIDM1LFxuICAgICAgMTgsXG4gICAgICAxOTcsXG4gICAgICAyNDYsXG4gICAgICAyMTQsXG4gICAgICAyNDgsXG4gICAgICAxODIsXG4gICAgICAxOTUsXG4gICAgICAxNTMsXG4gICAgICAyMjIsXG4gICAgICAxNDksXG4gICAgICAyMFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IGZhbHNlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTgzLFxuICAgICAgMjM3LFxuICAgICAgMTM4LFxuICAgICAgMjMzLFxuICAgICAgODksXG4gICAgICAyNTQsXG4gICAgICA3NyxcbiAgICAgIDI1LFxuICAgICAgMTE3LFxuICAgICAgMTIxLFxuICAgICAgMTIyLFxuICAgICAgMTc2LFxuICAgICAgMjYsXG4gICAgICAxNTcsXG4gICAgICA0OSxcbiAgICAgIDYwLFxuICAgICAgMTg1LFxuICAgICAgMjM0LFxuICAgICAgMjA5LFxuICAgICAgODBcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNQcTQ3NWdFRUpDbTlyRUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjFGWjRteWRCd1ZndHg4SHdGd0FsVWpSK01ETHo4RXMwTFd5QWE1V0RvVWc9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiZk5CeDhua2p4VGF2NVR5bHlUc3VjMjZONXJZdVlra1h5WllUVTdnMzlzZTlzNHFNbUNkZC9Sd05UWmRFSXFGOWdMODg1WnVVRmYzSTZNTGVTN0p2Qmc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiTWVhZ0lQbVFYV0h1NHVQZFpyOUxjcWtRRjIvamt2YlpXL1NhYlJJa1NxVFBGOG8vdDBuNURKZ1RCNmtvVW5QNlVtbHNXcDhIYUlnN0ZsOElxSEZmQ1E9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ4MDU3NTM2MjA3OjZAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjI3NDkyOTg0OTI0NTgyOTo2QGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIkhvcGVmdWxsefCflYrvuI/wn4y08J+ltPCfkbnwn5iHXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ4MDU3NTM2MjA3OjZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICA4MixcbiAgICAgICAgICA1MixcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICA1MixcbiAgICAgICAgICA0NSxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDE2MSxcbiAgICAgICAgICA3MlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzE1MzExMzgwLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSVVCXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFJVUEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJKUnVYV1VwYjEvNXREakVkTDBOS0hXWXdQOW5jUEVDS2NmN1lpOUY5Yk1ZPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjU4OTkzODIsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUlVQi5qc29uIjogIntcImtleURhdGFcIjpcImFjcUF5TnhNWGZ3c084K3JKa2FQblJPQU5oNjFmbEx5VUNLZzVFT2JpUmM9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTEyNTg5OTM4MyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE1MzA3MDg2MTM1XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSVVDLmpzb24iOiAie1wia2V5RGF0YVwiOlwiK1E2Sk9ZTFRNK2RRQlU4UkNYUG1lV2crdTNFbW4yc1pvODlQcksyRG5zbz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTI1ODk5Mzg0LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTUzMDc4Nzg4NTVcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFJVUQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJGejVWSG1MM2ppV2FzOVRFYnFxVjF4NWlmMGtoVDBpQkFCOHJMbFd1a1M4PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjU4OTkzODUsXCJjdXJyZW50SW5kZXhcIjoyLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMl19LFwidGltZXN0YW1wXCI6XCIxNzE1MzExMzMzMzM4XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSVVFLmpzb24iOiAie1wia2V5RGF0YVwiOlwiMzFKaDVxRlBlSHhnSVYvck1aRzJlelNsdUFqYXFrbUVHYUk3ZHMvVldJOD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTI1ODk5Mzg1LFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTUzMTEzNDAxMzRcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.4",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "hopefully",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "hopeful",
  ownername:process.env.OWNER_NAME|| "hopefully",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
